### ISSUE TITLE
Request for Code and Settings for Table 1 Atmospheric Retrievals

### ISSUE THREAD

**Issue by hzy24** [timothygebhard/ml4ptp#1]
First of all, thank you for sharing your work and making the code available for the astronomy community!

I found the methodology described in your paper "Parameterizing Pressure–Temperature Profiles of Exoplanet Atmospheres with Neural Networks" both innovative and highly informative. Your paper and methodology have inspired me to further develop this approach by constructing a physically meaningful parameter 'z' to parameterize the pressure-temperature curves, aiming to extend and advance this method.

To align my experiments with your results, could you please provide the code and detailed settings used for the atmospheric retrievals in Table 1? This information would be incredibly helpful for my research.

Thank you in advance for considering my request. If there are any additional requirements or conditions for accessing this code, please feel free to let me know, and I would be happy to discuss further.

**Comment by timothygebhard** [comment]
Hi! 

Running the retrievals in sec. 4.4 and appendix C was the only part of the paper that I did not do myself; hence the code for it is not part of this repository. I checked with my co-authors (E. Alei and B. Konrad specifically), and they told me that:

> The retrieval code is, now, still not easily usable by a wider audience. It is currently set up to work for the ETH cluster, but not outside of it. However, we are in the process of polishing it, documenting it, and releasing it open source soon (likely in a few months).

If you would rather not wait that long, the retrieval framework is also described in more detail in [Konrad et al. (2022)](https://ui.adsabs.harvard.edu/abs/2022A%26A...664A..23K/abstract) and [Alei et al. (2022b)](https://ui.adsabs.harvard.edu/abs/2022A%26A...665A.106A/abstract). Hope this helps!

**Comment by hzy24** [comment]
Thank you for your prompt and informative response! I completely understand the situation, and I appreciate the efforts you're making to polish and release the code soon. I will definitely keep an eye out for the open-source release in the coming months.

In the meantime, I’ll take a closer look at the retrieval framework described in Konrad et al. (2022) and Alei et al. (2022b), as you suggested. That should be helpful for continuing my research.

Thank you again for your assistance, and I look forward to the release of the code！！
